### ISSUE TITLE
Question about heatmap

### ISSUE THREAD

**Issue by Baeksweety** [Wayfear/BrainNetworkTransformer#1]
Sorry to bother you, but I have some questions about the heatmaps in the paper and would like to ask. If you don't mind, I hope you can tell me what data Figure3(b) is drawn with.

**Comment by Wayfear** [comment]
The average attention of the first MASH layer.

**Comment by xiaofochai** [comment]
I want to draw the heatmap like the figure in your paper, would you mind share your visualization code with me?

>

**Comment by xiaofochai** [comment]
> The average attention of the first MASH layer.

I want to draw the heatmap like the figure in your paper, would you mind share your visualization code with me?

**Comment by Baeksweety** [comment]
> The average attention of the first MASH layer.

Thank you very much!!! But I am still very curious about the details of the data, for example, why the heatmap has many thin lines further divided in each of the five areas?
I am sincerely waiting for your answer.

**Comment by Wayfear** [comment]
> 

I really want to share my code with you. However, after the NeurIPS submission, I did another work, and the code was modified to draw another figure. 

Here is some code API used to draw:

fig, ax = plt.subplots()
fig.set_size_inches(5, 5)

im = sns.heatmap(attention.T, cmap='coolwarm')

for pos in divide_line_pos:
    ax.axvline(x=pos, color='k', linestyle=':', linewidth=1)

For attention, the obtained attention matrix for one sample in Brain Network Transformer is a matrix A whose size is (head_num, node_size, node_size). What I do is average the first dimension of A and plot with the heatmap. Hope this can help you.

**Comment by Wayfear** [comment]
> > The average attention of the first MASH layer.
> 
> Thank you very much!!! But I am still very curious about the details of the data, for example, why the heatmap has many thin lines further divided in each of the five areas? I am sincerely waiting for your answer.

I use a functional module definition from [this repo](https://github.com/emergelab/hierarchical-brain-networks/blob/master/brainmaps/node_affiliations/AAc_all_maps.csv). Hope this reply is helpful.

**Comment by Baeksweety** [comment]
> 



> > > The average attention of the first MASH layer.
> > 
> > 
> > Thank you very much!!! But I am still very curious about the details of the data, for example, why the heatmap has many thin lines further divided in each of the five areas? I am sincerely waiting for your answer.
> 
> I use a functional module definition from [this repo](https://github.com/emergelab/hierarchical-brain-networks/blob/master/brainmaps/node_affiliations/AAc_all_maps.csv). Hope this reply is helpful.

okkkk!! Thank you for your help!!!
