### ISSUE TITLE
Question consultation

### ISSUE THREAD

**Issue by yaolp123** [Wayfear/BrainNetworkTransformer#2]
Dear authors: 
    Recently I  have looking at your this project and feel interested in it! And the URL is: https://github.com/Wayfear/BrainNetworkTransformer.  I have faced some questions, and ask for your help. The first one is that, the installed package pytorch is the gpu version?  And another question, is that,  this command in the github:

"python -m source --multirun datasz=100p model=bnt,fbnetgen,brainnetcnn,transformer dataset=ABIDE,ABCD repeat_time=5 preprocess=mixup"

I do not know where the source file and the why could I give these paramters, "multirun datasz, model, dataset ", because now I
have not find the source file, and feel confused why could we give these input paramters.
Thank you. I am looking forward to your reply Sincerely!

Best regards.

**Comment by Wayfear** [comment]
You can check the https://github.com/Wayfear/BrainNetworkTransformer/tree/main/source/conf folder. For example, "model=bnt" means use the config file, https://github.com/Wayfear/BrainNetworkTransformer/blob/main/source/conf/model/bnt.yaml, in the "model" folder.
