### ISSUE TITLE
Two questions regarding the 'abide.npy' dataset.

### ISSUE THREAD

**Issue by yangjenhao** [Wayfear/BrainNetworkTransformer#3]
Hello, I'd like to ask two questions regarding the 'abide.npy' dataset.

1. Is 'abide.npy' obtained after processing data following the command `git clone https://github.com/preprocessed-connectomes-project/abide` and using `python download_abide_preproc.py -d rois_cc200 -p cpac -s filt_global -o data/`?

2. How are the dimensions of 'final_timeseires' in ABIDE (1009, 200, 100) and 'final_pearson' (1009, 200, 200) determined, and what do they represent?

Thank you.

**Comment by Wayfear** [comment]
1. Here is the repo https://github.com/Wayfear/FBNETGEN/tree/main/util/abide I used to generate the abide dataset.
2. 'final_timeseires' in ABIDE (1009, 200, 100)  means (sample_size, roi_size, time-series length); 'final_pearson' (1009, 200, 200) means  (sample_size, roi_size, roi_size)

**Comment by yangjenhao** [comment]
I'd like to ask another question.
In the BrainNetworkTransformer model, is the "timeseries" data used solely for dimensionality checking, or does it serve other purposes as well?

Thank you.

**Comment by Wayfear** [comment]
I do not have a "HGSUM" model in my repo. Can you point out the code in this repo?

**Comment by yangjenhao** [comment]
Oh, sorry, I made a mistake. I was asking about the BrainNetworkTransformer model.

**Comment by Wayfear** [comment]
Yes, I do not use timeseries for BNT model

**Comment by yangjenhao** [comment]
Thanks you!
