### ISSUE TITLE
Train Accuracy & Test Accuracy？

### ISSUE THREAD

**Issue by RRRRendy** [Wayfear/BrainNetworkTransformer#6]
![image](https://github.com/Wayfear/BrainNetworkTransformer/assets/60954468/7e913d25-ddaa-4304-b1bf-0680a869c788)
为什么训练精度为56，测试精度为70+呢？
是我的程序跑错了还是什么问题呢？
希望得到您的回复，感激不尽！

**Comment by Wayfear** [comment]
Could it be possible that there are some differences in the package versions being used?
